### ISSUE TITLE
Any way of loading gif without blocking UI?

### ISSUE THREAD

**Issue by mourice** [bradmartin/nativescript-gif#12]
Gif rendering  happens on UI thread. Is there any way we can load the gif without blocking the UI thread.

**Comment by bradmartin** [comment]
I haven't seen any issue with rendering causing any issues. As for an option to handle the rendering I haven't looked at the native sources being used to determine if that's possible. You could skim through the native libs being used and see if they provide some options to offload the rendering but when I wrote this plugin I don't recall that being an option.

**Comment by mourice** [comment]
I am getting the gif to work without any issues my only concern is if I set the web url of the gif then for that time period to get the gif data from URL UI gets stuck. So is there any way we can have the data from url load asynchronously. I am testing this for ios

**Comment by bradmartin** [comment]
I suppose you could - but the native lib would need to be updated to make async calls (which I can't believe they don't already 🤔 ). At any rate - that's not something easily exposed via the plugin abstraction that this plugin provides. It would involve modifying the android/ios libs which I don't have knowledge to do the iOS side and not really any time to modify the java lib for android either at this time. Something you could do is possibly pull down the .gif sources yourself via NativeScripts http module and save them to the file-system and then serve the .gif from the local file-system. This would be an okay approach if you know what urls will be used, if not then of course this isn't that great. Although NativeScripts http calls are all async so they won't block anything so it still could benefit you if you wanted to try loading them locally instead of the url to the native lib.

**Comment by idroxid** [comment]
Nothing new on this topic ?
I'm displaying GIFs in a ListView and it blocks the UI while loading the GIFs.

**Comment by bradmartin** [comment]
@idroxid - sorry, I haven't really had time to support the plugin. I think there is at least one other plugin that supports GIFs and uses different native implementation. I don't recall specifically but want to say I looked at the native android lib being used in this plugin and there wasn't anything evident to me that would make the network run on the main thread it looked to be correctly implemented. Other than that, I'm not sure right now and haven't looked in the code base for a long time.
