### ISSUE TITLE
pl is not defined

### ISSUE THREAD

**Issue by lxmw001** [bradmartin/nativescript-gif#8]
Hi, 
I am developing an app and need to show a gif file in it, but when I try to use your plugin, this not work.
I get this error when I run the app:
![error gif](https://cloud.githubusercontent.com/assets/17038759/20035130/c4a48404-a3a5-11e6-9b05-cd6f615ef671.png)

**Comment by bradmartin** [comment]
Please do the following: https://bradmartin.net/2016/07/20/ahhh-this-nativescript-plugin-doesnt-work/

Your issue is the native library isn't compiled into your app so uninstalling the old .apk, then rebuilding in order to compile the dependency into your app, then running the new build will fix this problem. Hope that helps. The blog post has some good info to explain why you need to do this with plugins that use native libraries 👍

**Comment by lxmw001** [comment]
Thanks for your help, now the app works good, but the problem is in the android emulator, in the Genymotion emulator the app works fine (my error).
:+1:

**Comment by bradmartin** [comment]
Yea I use Genymotion myself so I can't help much on any android emulator issues. If the plugin is working feel free to close this issue 👍

**Comment by lxmw001** [comment]
:+1:
