### ISSUE TITLE
Not working in Nativescript Core

### ISSUE THREAD

**Issue by Ebineshwar** [bradmartin/nativescript-gif#9]
Hi 

I tried using your plugin, but it didnt work for me

When i do npm install also its not show in the plugin list like the other plugins

Can you please help me out with the same

**Comment by bradmartin** [comment]
Hi @Ebineshwar -

try running `tns plugin add nativescript-gif` instead of the npm install command.
After that could you uninstall any old versions of the app you're working on from any simulators/devices. Do a new build with `tns build android` (or ios if you're doing ios). Next `tns run android` and everything should work as expected on the device/emulator you install the new .apk on.  This post I did can provide some more info https://bradmartin.net/2016/07/20/ahhh-this-nativescript-plugin-doesnt-work/

**Comment by Ebineshwar** [comment]
Hi  @bradmartin  

Thanks a lot for a quick reply. The issue got solved like you said. It seems i cant access gifs from app resource folders, is there any workaround for it ?

**Comment by bradmartin** [comment]
There's a way to read the file string and parse it correctly but I'd just
put them locally in the app and reference them from there instead, that
should work fine for now. If you want to look at how to do the parsing you
can check the source code for the image module in the NS core and I'll
gladly accept a PR for it, I just don't have the time to do it right now :)

**Comment by Ebineshwar** [comment]
Sure, i will try to do it when i get time. Thanks for your help
